### ISSUE TITLE
[Suggestion] Compact view + Batch Uninstall

### ISSUE THREAD

**Issue by TeddStriker** [javiersantos/MLManager#12]
Thanks for this app, finally found a simple, ad free (for now at least :) ) APK manager, and its open source, which is definitely a plus. 

What I'd like to suggest is the option to batch uninstall APK's by some sort of selection (checkboxes or something of the sort), and preferably, the option for a compact view like this one:

 ![Uninstaller](https://lh4.ggpht.com/fVGpY7hEGpoHUCPQymt7riEnGOwRwv8PDIggQt1MuX02o4mxpq0PrMbOhU8AEr6p8A=h310) 

It would make going through huge lists of programs a lot easier.

Best regards.

**Comment by javiersantos** [comment]
Thanks for your suggestion. I will work on a batch feature really soon.

**Comment by javiersantos** [comment]
The latest [2.x release](https://play.google.com/store/apps/details?id=com.javiersantos.mlmanager) now includes a batch feature to manage multiple apps.

Thank you.
