### ISSUE TITLE
FAB in kitkat is square

### ISSUE THREAD

**Issue by robertmathew** [javiersantos/MLManager#14]
![screenshot_2015-06-17-11-11-46](https://cloud.githubusercontent.com/assets/2344947/8200385/e93bc7cc-14e1-11e5-86a6-e760113f9dbf.png)

Maybe the shadow is causing the FAB to show as the square.

**Comment by robertmathew** [comment]
https://code.google.com/p/android/issues/detail?id=175067
Hope this helps.

**Comment by javiersantos** [comment]
Thanks @robertmathew. I'll apply a fix as soon as possible.

In addition I will move to the AppCompat (v22.2.0) widget instead of using FloatingActionButton library (third party).

**Comment by robertmathew** [comment]
Great. Thanks.

**Comment by javiersantos** [comment]
Finally I replaced the actual library by another one and also fixed the issue mentioned (no more squares anymore) https://github.com/javiersantos/MLManager/commit/3b0732807d47bf4f6ce8313bbb0c33983668b5fb

Thanks.
