### ISSUE TITLE
Selected drawer item is wrong

### ISSUE THREAD

**Issue by robertmathew** [javiersantos/MLManager#15]
![screenshot_2015-06-17-15-05-50](https://cloud.githubusercontent.com/assets/2344947/8204084/ae8067e2-1503-11e5-9611-3a74037a5f4f.png)

After returning from AboutActivity, the selected drawer item is still About. 
Isn't the selected item should be previous selected item?

**Comment by javiersantos** [comment]
Fixed https://github.com/javiersantos/MLManager/commit/6e996eafe6fc5333c8953588717778ee947d1783

Thanks.
