### ISSUE TITLE
Crowdsourced Translations (e. g. with Transifex)

### ISSUE THREAD

**Issue by SweetLion** [javiersantos/MLManager#2]
Hey Javier,
thank you very much for your awesome app!
What do you think of using Transifex ( https://www.transifex.com/ ) for translations? 
Because the ML Manager is open source, setting up Transifex is for free.

**Comment by javiersantos** [comment]
Thanks for your interesting. Translations for ML Manager are available on Crowdin: https://crowdin.com/project/ml-manager
