### ISSUE TITLE
Translate "Search..." string

### ISSUE THREAD

**Issue by 7ShaYaN7** [javiersantos/MLManager#21]
I am translating the app, almost done but as you can see in the following SS, the "Search..." string doesn't exist in strings.xml file and after somewhile and deal with the code I couldn't find anything related.

![untitled](https://cloud.githubusercontent.com/assets/10985542/8765920/a0723c58-2e39-11e5-9c1f-37e73eaef20d.png)

plz guide me through this.

**Comment by javiersantos** [comment]
Thanks @7ShaYaN7. It has been fixed with this commit https://github.com/javiersantos/MLManager/commit/e629e75998a3456e9594f68812406b6c38b489d2

It is now using the value *search_hint* of strings.xml https://github.com/javiersantos/MLManager/blob/master/app/src/main/res/values/strings.xml#L24

**Comment by 7ShaYaN7** [comment]
Tnx man, good code!
