### ISSUE TITLE
banner_troll.png

### ISSUE THREAD

**Issue by 7ShaYaN7** [javiersantos/MLManager#22]
After all of investigation I couldn't find when and where the **drawable/banner_troll.png** is displayed?

and then, can you provide some documentation materials for **extractMLManagerPro** method that the above image used there.

**Good Time and Code!**

**Comment by javiersantos** [comment]
```extractMLManagerPro``` is called when the user try to extract ML Manager Pro. This method copy the drawable instead of the APK.
