### ISSUE TITLE
RTL alignment

### ISSUE THREAD

**Issue by 7ShaYaN7** [javiersantos/MLManager#24]
Hi there,
how to make the app name in title bar and the drawer align right (i.e. the name move to the right side of screen and the drawer open from the right side) in RTL languages.

I try some codes as following:

in onCreate method in LaunchActivity:

```
        Locale.setDefault(new Locale("fa"));

        Configuration config = new Configuration();

        config.locale = new Locale("fa");

        getBaseContext()
                .getResources()
                .updateConfiguration(
                        config,
                        getBaseContext().getResources()
                                .getDisplayMetrics());
```

and then in application tag in AndroidManifest:

```
android:supportsRtl="true"
```

but it gets wrong and buggy on different phones and make the layouts disarranged.

The intention of discussing this issue is to conveying more realistic RTL app sense when it is shown in RTL languages.

**Comment by javiersantos** [comment]
Well, I think you could use something like this.

A method to detect RTL. Then you could use ```isRTL``` in the code:
```java
public static boolean isRTL() {
    return isRTL(Locale.getDefault());
}

private static boolean isRTL(Locale locale) {
    final int directionality = Character.getDirectionality(locale.getDisplayName().charAt(0));
    return directionality == Character.DIRECTIONALITY_RIGHT_TO_LEFT ||
           directionality == Character.DIRECTIONALITY_RIGHT_TO_LEFT_ARABIC;
}
```

On the activity ```onCreate```
```java
if (isRTL) {
    getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
}
```

Don't forget to add ```android:supportsRtl="true"``` to the AndroidManifest.xml

Take note that the ```minSdkVersion``` has to be 17.
