### ISSUE TITLE
Do You Have To Use GPL?

### ISSUE THREAD

**Issue by opticyclic** [javiersantos/MLManager#27]
AOSP uses Apache 2.0 https://source.android.com/source/licenses.html

Apache licensed work can be included in GPL work but GPL work can't be included in Apache work.
http://www.apache.org/licenses/GPL-compatibility.html

Do you have to use GPL?

**Comment by javiersantos** [comment]
According to the GPL license: "Apache software can be included in GPL projects - the GPL accepts the Apache license. Incompatible, if a Apache software is a derivative of a GPL project. The final product must be distributed under GPL."

ML Manager is not using any derivate work of a Apache software.

**Comment by opticyclic** [comment]
I meant that I wanted to distribute under the Apache license but would have to use GPL as you are using GPL.
Is there any particular reason why you are using GPL?

**Comment by javiersantos** [comment]
Yes. The main reason is to require derivative works to publish the source code too. I also wanted to ensure that derivative works from the project maintain the same license, without allowing switch to another one.

**Comment by opticyclic** [comment]
Fair enough. Thanks for the clarification.
