### ISSUE TITLE
Rules For Derivative Works

### ISSUE THREAD

**Issue by opticyclic** [javiersantos/MLManager#28]
I would like to create a derivative of MLManager.
Is it OK to keep the same package names as yours?
It would make pulling in upstream fixes easier.

**Comment by javiersantos** [comment]
If you want to create a derivate work for testing purposes (not publishing it on Internet) is OK to use the same package name. However, if you want to publish it, I recommend you to change the package name for this reason:

* You will not be able to publish on some App Stores where ML Manager is published already.
* It does not represent the original work.
* Users will not be able to know who is the author of the derivated work at a first look.

**Comment by opticyclic** [comment]
I didn't mean the android package/application id, I meant the Java packages.
e.g. src/main/java/com/javiersantos/mlmanager/ 

Should I refactor those names too?

**Comment by javiersantos** [comment]
Well, you don't need to change the package names, but I would swear that you need to do a refactor of the Java packages to change the applicacionId: http://stackoverflow.com/questions/4025369/how-to-change-package-name-of-an-android-application

**Comment by opticyclic** [comment]
OK. No problem. Thanks for providing such a nice looking open source application for others to learn from.
