### ISSUE TITLE
Is 1.0.5.x meant to be a release?

### ISSUE THREAD

**Issue by krt16s** [javiersantos/MLManager#32]
You haven't tagged any of those releases and there commits to both branches. Are the 1.0.5.x versions meant to be released or are they development builds?

**Comment by M2ck** [comment]
I think we have the anwser to this question here, [About the future of ML Manager](https://plus.google.com/+JavierSantos/posts/Hpx9DVVSVhn), isn't he @javiersantos?
It's really sad but your reasons are understandable, so you will release at least the version 1.0.5.3 on F-Droid, right?

**Comment by javiersantos** [comment]
@M2ck As you said, that is the main reason. Anyway, the 1.0.5.x releases are just specific updates for Google Play to allow Batch.com support but nothing more, so the latest one is the 1.0.4 update. BTW, the `batchcom` branch won't compile without a proper Batch.com key.

**Comment by javiersantos** [comment]
Oh well, I just saw that there are some commits not included in the latest 1.0.4 update. I'll release the 1.0.4.1 on GitHub asap. Sorry for the mistake.

**Comment by M2ck** [comment]
Thanks of let us know, maybe you should update the README file with a status indicator like "Depreciated" or "closed source".

**Comment by javiersantos** [comment]
Seems there is a problem when building the latest update on F-Droid. Could you have a look @krt16s?

https://f-droid.org/wiki/page/com.javiersantos.mlmanager/lastbuild_21

Thanks.
