### ISSUE TITLE
CrowdIn translation

### ISSUE THREAD

**Issue by GameRebellStudio** [javiersantos/MLManager#33]
Hello, I've already translated all strings in Czech translation of ML Manager. Translation is completely **done** and I checked it. I hope everything is correct :-) What's next? 
Greetings _Game Rebell Studio._

**Comment by M2ck** [comment]
@javiersantos same thing for french language, translation completed and approved. Please consider a translation update asap.
Thanks.

**Comment by javiersantos** [comment]
All translations have been updated for the 2.x release. Could you have a look? Thanks.

**Comment by M2ck** [comment]
@javiersantos french translation is already up to date!

**Comment by GameRebellStudio** [comment]
@javiersantos I'm working on new translation, will be done soon:-)
