### ISSUE TITLE
Storage permission on Android 6.0.x

### ISSUE THREAD

**Issue by Primokorn** [javiersantos/MLManager#34]
Hi,
ML Manager should be able to ask this permission at first start up.
We can't extract an apk as long as we grant the permission in the App permissions screen.

Thank you.

**Comment by javiersantos** [comment]
The latest update ([v1.0.4.1](https://github.com/javiersantos/MLManager/releases/tag/v1.0.4.1)) should fix the storage permission on Android 6.0, isn't it?

**Comment by Primokorn** [comment]
Waiting for the F-droid update.

**Comment by javiersantos** [comment]
According to the [f-droid's wiki](https://f-droid.org/wiki/page/com.javiersantos.mlmanager#1.0.4.1):
> We can't build this version: The build for this version was manually disabled. Reason: third party maven repo
