### ISSUE TITLE
Show navigation bar in black --> requires Android 5.0+

### ISSUE THREAD

**Issue by SweetLion** [javiersantos/MLManager#4]
![screenshot_settings](https://cloud.githubusercontent.com/assets/12447257/7901808/d203e358-079b-11e5-9f22-488abbda1d09.png)

The setting ,,Show navigation bar in black" requires Android 5.0 or higher. Could you please handle this setting like the setting ,,Primary color" (add Requires Android 5.0+ and grey it out on pre-Lollipop devices)? Thanks Javier.

**Comment by javiersantos** [comment]
Fixed: https://github.com/javiersantos/MLManager/commit/d40d104aa09842e171054ae73ea9d2e549ccfd19

Thanks.
