### ISSUE TITLE
FAB shows above content

### ISSUE THREAD

**Issue by alorma** [javiersantos/MLManager#6]
In this case, is justified to not have the FAB, you can use the icon in ActionBar, it will be more clear

**Comment by javiersantos** [comment]
Do you mean the FAB included in the details of every app? Maybe another solution:
* Remove FAB to share.
* Remove "Tap to open" card view.
* Add FAB to open app.
* Include share button in ActionBar.

**Comment by javiersantos** [comment]
I have added more features to the FAB. Feel free to open again the issue if you think it could be improved even more.

Thanks.
